dataSource:
  host: 47.254.245.66
  database: gkqr
  user: root
  password: gk
  port: 3306
  maxLifeTime: 120
  maxOpenConns: 10
  maxIdleConns: 5
kafka :
  host: 218.0.49.239
  port: 9092
redis:
  host: 127.0.0.1:6379
  password:
  db: 10
