dataSource:
  host: 128.0.0.1
  database: 123456
  user: root
  password: 123456
  port: 3306
  maxLifeTime: 120
  maxOpenConns: 10
  maxIdleConns: 5
kafka :
  host: 127.0.0.1
  port: 9092
redis:
  host: 127.0.0.1:6379
  password:
  db: 10
